config/routes.rb
Rails.application.routes.draw do
    root 'home#index'
  devise_for :users

  resources :quotes do
    member do
      put "like" => "quotes#upvote"
      put "dislike" => "quotes#downvote"
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Quote, user_id: user.id
  end
end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :user
  acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :quotes
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to quotes_path
    end
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!
  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all.order(:cached_votes_score => :desc)
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @user = current_user
    @quote = @user.quotes.build(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to quotes_path, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end

  def update
    authorize! :manage, @quote

  end
  def destroy
    authorize! :manage, @quote

  end
end
  def destroy
  @quote = current_user.quotes.find(params[:id])
  @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end

  end



  def upvote
    @quote.upvote_from current_user
    redirect_to quotes_path
  end
  def downvote
    @quote.downvote_from current_user
    redirect_to quotes_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:quote, :autor, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/home/index.html.erb
<div class="home">
  <h2> Welcome on </h2>
  <h1>MMI's quotes</h1>
  <h5>Here you can save and share every students's or teachers's best remarks.</br> To continue please
  <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Login", new_user_session_path %>.</h5>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MMI's quotes</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application','packery-docs' 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet">
    <link rel="stylesheet" href="/font-awesome-4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Inconsolata:400,700|Palanquin:200,400,600" rel="stylesheet">
</head>
  <body>
      <% if user_signed_in? %>
      <div class="navbar">
        <div class="logo">
          <%= link_to 'MMIs quotes', quotes_path %>
        </div>
        <div>
          <h6><%= link_to '+ New Quote', new_quote_path %></h6>
          <h3><%= link_to 'Edit profile', edit_user_registration_path %></h3>
          <h3><%= link_to 'Log out', destroy_user_session_path, method: :delete %></h3>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>
  <footer>
    <% if user_signed_in? %>
      <p>Logged as <strong><%= current_user.email %></strong>.</p>
    <% end %>
    <p id="notice"><%= notice %></p>
    <p> MMI's quotes © coded by Emeline Bailleul</p>
  </footer>

</html>

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :quote %><br>
    <%= f.text_area :quote, :class => 'new'%>
  </div>
  <div>
    <%= f.label :autor%><br>
    <%= f.text_field :autor, :class => 'new'%>
  </div>
  <div class="button-users">
    <%= f.submit%>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<div class="users">
  <div class="button">
    <%= link_to :back do%>
      <i class="fa fa-chevron-left fa-lg" aria-hidden="true"></i>
    <% end %>
  <div class="title">
    <h1>Editing Quote</h1>
  </div>
  <div class="container">
    <%= render 'form' %>
  </div>
  </div>
</div>

app/views/quotes/index.html.erb
<div class="grid">

  <% @quotes.each do |quote| %>

    <div class="grid-item , card ">

        <div class="button-admin">
          <% if can? :destroy, quote %>
            <%= link_to quote, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fa fa-trash" aria-hidden="true"></i>
            <% end %>
          <% end %>
          <% if can? :update, quote %>
            <%= link_to edit_quote_path(quote) do %>
              <i class="fa fa-pencil" aria-hidden="true"></i>
            <% end %>
          <% end %>
        </div>

        <div class="quotes">
            <p>"<%= quote.quote %>"</p>
        </div>

        <div class="under">
          <h4>By <%= quote.autor %></h4>
          <div class="like">
            <%= link_to like_quote_path(quote), :class => "change", method: :put do%>
              <i class="fa fa-heart" aria-hidden="true"></i><%= quote.get_upvotes.size %>
            <% end %>
            <%= link_to dislike_quote_path(quote), method: :put do %>
              <i class="fa fa-times" aria-hidden="true"></i><%= quote.get_downvotes.size %>
            <% end %>
          </div>
        </div>
  </div>
<% end %>
<script>
  $('.grid').packery({
    itemSelector: '.grid-item',
    percentPosition: true,
    gutter: 6
  });
</script>
<script>
$( document).ready(function() {
    $('.change').click(function(){
    $(this).find('i.fa').removeClass('fa-heart-o').addClass('fa-heart');
    })
});


</script>
</div>

app/views/quotes/new.html.erb
    <div class="users">
      <div class="button">
        <%= link_to quotes_path do%>
        <i class="fa fa-chevron-left" aria-hidden="true"></i>
        <% end %>
      </div>
      <div class="title">
        <h2><strong>New Quote</strong></h2>
      </div>
      <div class="container">
        <%= render 'form' %>
      </div>
  </div>

app/views/quotes/show.html.erb
  <div class="grid">
    <div class="grid-item , cardshow">
      <div class="button">
        <%= link_to quotes_path do%>
          <img src="/return.svg">
        <% end %>
        <%= link_to edit_quote_path(@quote) do %>
          <img src="/edit.svg">
        <% end %>
      </div>
      <div class="quotes">
          <p>"<%= @quote.quote %>"</p>
          <h4>By <%= @quote.autor %> | <%= @quote.date %></h4>
      </div>
    </div>
</div>